// Code generated by 'yaegi extract github.com/MobinYengejehi/core/base/num'. DO NOT EDIT.

package basesymbols

import (
	"reflect"
)

func init() {
	Symbols["github.com/MobinYengejehi/core/base/num/num"] = map[string]reflect.Value{}
}
