// Code generated by 'yaegi extract github.com/MobinYengejehi/core/paint'. DO NOT EDIT.

package coresymbols

import (
	"github.com/MobinYengejehi/core/paint"
	"reflect"
)

func init() {
	Symbols["github.com/MobinYengejehi/core/paint/paint"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ClampBorderRadius": reflect.ValueOf(paint.ClampBorderRadius),
		"EdgeBlurFactors":   reflect.ValueOf(paint.EdgeBlurFactors),
		"NewImageRenderer":  reflect.ValueOf(&paint.NewImageRenderer).Elem(),
		"NewPainter":        reflect.ValueOf(paint.NewPainter),
		"NewSVGRenderer":    reflect.ValueOf(&paint.NewSVGRenderer).Elem(),
		"NewSourceRenderer": reflect.ValueOf(&paint.NewSourceRenderer).Elem(),
		"RenderToImage":     reflect.ValueOf(paint.RenderToImage),
		"RenderToSVG":       reflect.ValueOf(paint.RenderToSVG),

		// type definitions
		"Painter": reflect.ValueOf((*paint.Painter)(nil)),
		"State":   reflect.ValueOf((*paint.State)(nil)),
	}
}
