// Code generated by 'yaegi extract github.com/MobinYengejehi/core/content'. DO NOT EDIT.

package coresymbols

import (
	"github.com/MobinYengejehi/core/content"
	"reflect"
)

func init() {
	Symbols["github.com/MobinYengejehi/core/content/content"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewContent":      reflect.ValueOf(content.NewContent),
		"NewPageInitFunc": reflect.ValueOf(&content.NewPageInitFunc).Elem(),

		// type definitions
		"Content": reflect.ValueOf((*content.Content)(nil)),
	}
}
