// Code generated by "core generate -icons ."; DO NOT EDIT.

package cicons

import (
	_ "embed"

	"github.com/MobinYengejehi/core/icons"
)

var (
	//go:embed sign-in-with-google.svg
	SignInWithGoogle icons.Icon
)
